//go:build !ignore_autogenerated

/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Open5GS) DeepCopyInto(out *Open5GS) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Open5GS.
func (in *Open5GS) DeepCopy() *Open5GS {
	if in == nil {
		return nil
	}
	out := new(Open5GS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Open5GS) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Open5GSConfiguration) DeepCopyInto(out *Open5GSConfiguration) {
	*out = *in
	if in.Slices != nil {
		in, out := &in.Slices, &out.Slices
		*out = make([]Open5GSSlice, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Open5GSConfiguration.
func (in *Open5GSConfiguration) DeepCopy() *Open5GSConfiguration {
	if in == nil {
		return nil
	}
	out := new(Open5GSConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Open5GSFunction) DeepCopyInto(out *Open5GSFunction) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ServiceAccount != nil {
		in, out := &in.ServiceAccount, &out.ServiceAccount
		*out = new(bool)
		**out = **in
	}
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = new(bool)
		**out = **in
	}
	if in.ServiceMonitor != nil {
		in, out := &in.ServiceMonitor, &out.ServiceMonitor
		*out = new(bool)
		**out = **in
	}
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = make([]Open5GSService, len(*in))
		copy(*out, *in)
	}
	if in.DeploymentAnnotations != nil {
		in, out := &in.DeploymentAnnotations, &out.DeploymentAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Open5GSFunction.
func (in *Open5GSFunction) DeepCopy() *Open5GSFunction {
	if in == nil {
		return nil
	}
	out := new(Open5GSFunction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Open5GSList) DeepCopyInto(out *Open5GSList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Open5GS, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Open5GSList.
func (in *Open5GSList) DeepCopy() *Open5GSList {
	if in == nil {
		return nil
	}
	out := new(Open5GSList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Open5GSList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Open5GSReference) DeepCopyInto(out *Open5GSReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Open5GSReference.
func (in *Open5GSReference) DeepCopy() *Open5GSReference {
	if in == nil {
		return nil
	}
	out := new(Open5GSReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Open5GSService) DeepCopyInto(out *Open5GSService) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Open5GSService.
func (in *Open5GSService) DeepCopy() *Open5GSService {
	if in == nil {
		return nil
	}
	out := new(Open5GSService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Open5GSSlice) DeepCopyInto(out *Open5GSSlice) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Open5GSSlice.
func (in *Open5GSSlice) DeepCopy() *Open5GSSlice {
	if in == nil {
		return nil
	}
	out := new(Open5GSSlice)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Open5GSSpec) DeepCopyInto(out *Open5GSSpec) {
	*out = *in
	in.AMF.DeepCopyInto(&out.AMF)
	in.AUSF.DeepCopyInto(&out.AUSF)
	in.BSF.DeepCopyInto(&out.BSF)
	in.MongoDB.DeepCopyInto(&out.MongoDB)
	in.NRF.DeepCopyInto(&out.NRF)
	in.NSSF.DeepCopyInto(&out.NSSF)
	in.PCF.DeepCopyInto(&out.PCF)
	in.SCP.DeepCopyInto(&out.SCP)
	in.SMF.DeepCopyInto(&out.SMF)
	in.UDM.DeepCopyInto(&out.UDM)
	in.UDR.DeepCopyInto(&out.UDR)
	in.UPF.DeepCopyInto(&out.UPF)
	in.WebUI.DeepCopyInto(&out.WebUI)
	in.Configuration.DeepCopyInto(&out.Configuration)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Open5GSSpec.
func (in *Open5GSSpec) DeepCopy() *Open5GSSpec {
	if in == nil {
		return nil
	}
	out := new(Open5GSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Open5GSStatus) DeepCopyInto(out *Open5GSStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Open5GSStatus.
func (in *Open5GSStatus) DeepCopy() *Open5GSStatus {
	if in == nil {
		return nil
	}
	out := new(Open5GSStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Open5GSUser) DeepCopyInto(out *Open5GSUser) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Open5GSUser.
func (in *Open5GSUser) DeepCopy() *Open5GSUser {
	if in == nil {
		return nil
	}
	out := new(Open5GSUser)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Open5GSUser) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Open5GSUserList) DeepCopyInto(out *Open5GSUserList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Open5GSUser, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Open5GSUserList.
func (in *Open5GSUserList) DeepCopy() *Open5GSUserList {
	if in == nil {
		return nil
	}
	out := new(Open5GSUserList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Open5GSUserList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Open5GSUserSpec) DeepCopyInto(out *Open5GSUserSpec) {
	*out = *in
	out.Open5GS = in.Open5GS
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Open5GSUserSpec.
func (in *Open5GSUserSpec) DeepCopy() *Open5GSUserSpec {
	if in == nil {
		return nil
	}
	out := new(Open5GSUserSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Open5GSUserStatus) DeepCopyInto(out *Open5GSUserStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Open5GSUserStatus.
func (in *Open5GSUserStatus) DeepCopy() *Open5GSUserStatus {
	if in == nil {
		return nil
	}
	out := new(Open5GSUserStatus)
	in.DeepCopyInto(out)
	return out
}
