apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "open5gs-operator.fullname" . }}-open5gs-viewer-role
  labels:
  {{- include "open5gs-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - net.gradiant.org
  resources:
  - open5gs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - net.gradiant.org
  resources:
  - open5gs/status
  verbs:
  - get