# permissions for end users to view open5gs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: open5gs-operator
    app.kubernetes.io/managed-by: kustomize
  name: open5gs-viewer-role
rules:
- apiGroups:
  - net.gradiant.org
  resources:
  - open5gs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - net.gradiant.org
  resources:
  - open5gs/status
  verbs:
  - get
